#!/bin/bash

# --- Configuration ---
BG_SRC="wallpaper.jpg"         # Your base image
HEADER="header.png"            # Generated by the Python script
FOOTER="footer.png"            # Generated by the Python script
OUTPUT="pentoo-plymouth.png"

# Target Resolution (Standard HD)
RES="1920x1080"
BG_COLOR="black"               # Fills gaps if wallpaper is wrong aspect ratio

# Offsets (Adjust based on your progress bar location)
HEADER_Y_OFFSET=150            # Distance from top
FOOTER_Y_OFFSET=100            # Distance from bottom

echo "🎨 Compositing Pentoo Splash..."

# 1. Resize/Crop background to 1080p and center it
# 2. Layer the Header at the top (North) with offset
# 3. Layer the Footer at the bottom (South) with offset
convert "$BG_SRC" \
    -resize "$RES^" -gravity center -extent "$RES" -background "$BG_COLOR" \
    "$HEADER" -gravity north -geometry "+0+$HEADER_Y_OFFSET" -composite \
    "$FOOTER" -gravity south -geometry "+0+$FOOTER_Y_OFFSET" -composite \
    "$OUTPUT"

echo "✅ Success! Created $OUTPUT"
echo "💡 Tip: Move this to /usr/share/plymouth/themes/pentoo/background.png"
