[theme]
name = "pentoo-terminator"
dirs = ["conf", "docs", "sources/preview", "assets/frames"]

[branding]
header_toml = "header.toml"
footer_toml = "footer.toml"

[build]
source = "sources/background.mp4"
mode = "animation" # or static
