[logo]
source = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk4rexs5d5i5ViT5eiwK8OD3p08ANI_TZmJ-0C7AecNg&s"
scale = 0.12          # 12% of screen width
mode = "neon"         # bw, invert, neon, plasma
glow_color = "#00FF00"

[placement]
# --- Corners ---
top_left      = true
top_right     = true
bottom_left   = false
bottom_right  = true

# --- Edges ---
top_center    = false
bottom_center = true
center_left   = false
center_right  = false

# --- Master ---
center        = false

[offsets]
margin = 40           # Pixels from the edge
